"""
Redis protocol package
"""

from .algo_stats_api import (
    ALGO_STATS_KEY_PREFIX,
    AlgoStatsData,
    increment_algo_stats,
    read_algo_stats,
    read_all_algo_stats,
    reset_algo_stats,
    write_algo_stats,
)
from .close_positions_command import (
    CLOSE_POSITIONS_COMMAND_KEY,
    clear_close_positions_command,
    get_close_positions_command,
    request_close_all_positions,
)
from .coalescing_batcher import CoalescingBatcher
from .connection import cleanup_redis_pool, get_redis_pool, get_retry_redis_client
from .converters import coerce_float, decode_redis_hash, decode_redis_value
from .kalshi_store import KalshiStore
from .market_normalization import ensure_market_metadata_fields
from .market_ownership import can_algo_own_market, can_algo_own_market_type, configure_ownership, get_required_owner
from .market_update_api import (
    MarketUpdateResult,
    request_market_update,
)
from .messages import IndexMetadata, InstrumentMetadata, MarketData, SubscriptionUpdate
from .persistence_manager import (
    RedisPersistenceManager,
    ensure_redis_persistence,
    get_redis_persistence_status,
)
from .probability_store import ProbabilityStore
from .restart_service_command import (
    RESTART_SERVICE_COMMAND_KEY,
    RestartServiceResult,
    clear_restart_service_command,
    clear_restart_service_result,
    get_restart_service_command,
    get_restart_service_result,
    request_restart_service,
    write_restart_service_result,
)
from .retry_client import RetryPipeline, RetryRedisClient
from .streams import (
    ALGO_EVENT_STREAM_PREFIX,
    CLOSE_POSITIONS_STREAM,
    EXCHANGE_EVENT_STREAM,
    SIGNALS_EDGE_CONSUMER_GROUP,
    SIGNALS_PEAK_CONSUMER_GROUP,
    SIGNALS_STRUCTURE_CONSUMER_GROUP,
    TRACKER_CONSUMER_GROUP,
    MessageHandler,
    RedisStreamSubscriber,
    StreamConfig,
    claim_pending_entries,
    decode_stream_response,
    ensure_consumer_group,
    stream_publish,
)
from .subscription_store import SubscriptionStore
from .toggle_service_command import (
    TOGGLE_SERVICE_COMMAND_KEY,
    ToggleServiceResult,
    clear_toggle_service_command,
    clear_toggle_service_result,
    get_toggle_service_command,
    get_toggle_service_result,
    request_toggle_service,
    write_toggle_service_result,
)
from .trading_toggle_api import (
    ALGO_TRADING_KEY_PREFIX,
    SIGNAL_COUNT_KEY_PREFIX,
    VALIDATED_COUNT_KEY_PREFIX,
    AlgoTradingConfig,
    delete_old_cooldown_keys,
    get_algo_max_contracts,
    get_algo_sample_rate,
    get_all_algo_trading_config,
    get_all_algo_trading_states,
    get_signal_counts,
    get_validated_counts,
    increment_signal_count,
    increment_validated_count,
    initialize_algo_trading_defaults,
    is_algo_trading_enabled,
    set_algo_max_contracts,
    set_algo_sample_rate,
    set_algo_trading_enabled,
    set_all_algo_trading_enabled,
    toggle_algo_trading,
)

__all__ = [
    "RetryPipeline",
    "RetryRedisClient",
    "can_algo_own_market",
    "can_algo_own_market_type",
    "configure_ownership",
    "get_redis_pool",
    "get_retry_redis_client",
    "get_required_owner",
    "cleanup_redis_pool",
    "RedisPersistenceManager",
    "ensure_redis_persistence",
    "get_redis_persistence_status",
    "SubscriptionStore",
    "SubscriptionUpdate",
    "InstrumentMetadata",
    "IndexMetadata",
    "MarketData",
    "CoalescingBatcher",
    "KalshiStore",
    "ensure_market_metadata_fields",
    "ProbabilityStore",
    "decode_redis_value",
    "decode_redis_hash",
    "coerce_float",
    "request_market_update",
    "MarketUpdateResult",
    "ALGO_TRADING_KEY_PREFIX",
    "AlgoTradingConfig",
    "SIGNAL_COUNT_KEY_PREFIX",
    "VALIDATED_COUNT_KEY_PREFIX",
    "delete_old_cooldown_keys",
    "get_algo_max_contracts",
    "get_algo_sample_rate",
    "get_all_algo_trading_config",
    "get_all_algo_trading_states",
    "get_signal_counts",
    "get_validated_counts",
    "increment_signal_count",
    "increment_validated_count",
    "initialize_algo_trading_defaults",
    "is_algo_trading_enabled",
    "set_algo_max_contracts",
    "set_algo_sample_rate",
    "set_algo_trading_enabled",
    "set_all_algo_trading_enabled",
    "toggle_algo_trading",
    "CLOSE_POSITIONS_COMMAND_KEY",
    "clear_close_positions_command",
    "get_close_positions_command",
    "request_close_all_positions",
    "RESTART_SERVICE_COMMAND_KEY",
    "RestartServiceResult",
    "clear_restart_service_command",
    "clear_restart_service_result",
    "get_restart_service_command",
    "get_restart_service_result",
    "request_restart_service",
    "write_restart_service_result",
    "TOGGLE_SERVICE_COMMAND_KEY",
    "ToggleServiceResult",
    "clear_toggle_service_command",
    "clear_toggle_service_result",
    "get_toggle_service_command",
    "get_toggle_service_result",
    "request_toggle_service",
    "write_toggle_service_result",
    "ALGO_STATS_KEY_PREFIX",
    "AlgoStatsData",
    "increment_algo_stats",
    "read_algo_stats",
    "read_all_algo_stats",
    "reset_algo_stats",
    "write_algo_stats",
    "ALGO_EVENT_STREAM_PREFIX",
    "CLOSE_POSITIONS_STREAM",
    "EXCHANGE_EVENT_STREAM",
    "MessageHandler",
    "RedisStreamSubscriber",
    "SIGNALS_EDGE_CONSUMER_GROUP",
    "SIGNALS_PEAK_CONSUMER_GROUP",
    "SIGNALS_STRUCTURE_CONSUMER_GROUP",
    "StreamConfig",
    "TRACKER_CONSUMER_GROUP",
    "claim_pending_entries",
    "decode_stream_response",
    "ensure_consumer_group",
    "stream_publish",
]
